const dummyData = [
    {
      reqNo: "REQ001",
      reqForm: "Form A",
      requser: "User1",
      materialRequestion: "Steel Rods",
      reqDate: "2025-02-01",
      status: "Pending",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',

    },
    {
      reqNo: "REQ002",
      reqForm: "Form B",
      requser: "User2",
      materialRequestion: "Cement Bags",
      reqDate: "2025-02-02",
      status: "Approved",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',
    },
    {
      reqNo: "REQ003",
      reqForm: "Form C",
      requser: "User3",
      materialRequestion: "Bricks",
      reqDate: "2025-02-03",
      status: "Rejected",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',
    },
    {
      reqNo: "REQ004",
      reqForm: "Form D",
      requser: "User4",
      materialRequestion: "Wood Planks",
      reqDate: "2025-02-04",
      status: "Pending",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',
    },
    {
      reqNo: "REQ005",
      reqForm: "Form E",
      requser: "User5",
      materialRequestion: "Nails",
      reqDate: "2025-02-05",
      status: "Approved",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',
    },
    {
      reqNo: "REQ006",
      reqForm: "Form F",
      requser: "User6",
      materialRequestion: "Glass Sheets",
      reqDate: "2025-02-06",
      status: "Rejected",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',
    },
    {
      reqNo: "REQ007",
      reqForm: "Form G",
      requser: "User7",
      materialRequestion: "PVC Pipes",
      reqDate: "2025-02-07",
      status: "Pending",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',
    },
    {
      reqNo: "REQ008",
      reqForm: "Form H",
      requser: "User8",
      materialRequestion: "Paint Cans",
      reqDate: "2025-02-08",
      status: "Approved",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',
    },
    {
      reqNo: "REQ009",
      reqForm: "Form I",
      requser: "User9",
      materialRequestion: "Electrical Wires",
      reqDate: "2025-02-09",
      status: "Rejected",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',
    },
    {
      reqNo: "REQ010",
      reqForm: "Form J",
      requser: "User10",
      materialRequestion: "Tiles",
      reqDate: "2025-02-10",
      status: "Pending",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',
    },
    {
      reqNo: "REQ011",
      reqForm: "Form K",
      requser: "User11",
      materialRequestion: "Concrete Blocks",
      reqDate: "2025-02-11",
      status: "Approved",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',
    },
    {
      reqNo: "REQ012",
      reqForm: "Form L",
      requser: "User12",
      materialRequestion: "Sand Bags",
      reqDate: "2025-02-12",
      status: "Rejected",
      createdAt:'2024-02-15T10:30:00Z',
      remarks: 'Everything looks good',
    }
  ];
  
  export const getDummyData = () => dummyData;
  
  export default dummyData;
  